# Generated by Django 4.0.6 on 2022-11-03 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(default='SOME STRING', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('quantity', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
    ]
