# Generated by Django 4.0.6 on 2022-11-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_order_detail_prod_id_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product'),
        ),
    ]
