# Generated by Django 4.0.6 on 2022-11-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_detail_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product', to_field='desc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(null=True, unique=True),
        ),
    ]
