# Generated by Django 4.0.6 on 2022-11-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_detail_prod_id_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
            preserve_default=False,
        ),
    ]
