# Generated by Django 4.0.6 on 2022-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ManyToManyField(to='base.category'),
        ),
    ]
