# Generated by Django 4.0.6 on 2022-11-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_product_cat_id_product_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
            preserve_default=False,
        ),
    ]
